version: '2'

services:
  servuo:
    build: ./servuo
    image: 'servuo-alpine'
    restart: always
#    mem_limit: 2048m
    ports:
    - "2593:2593"
    volumes:
      - ./servuo-data:/UO
    network_mode: host
#    command: ping localhost
